### ISSUE TITLE
Java Virtual Machine Error.

### ISSUE THREAD

**Issue by V1pr1n** [Ben-Bingham/Sprite-Generator-For-Minecraft#1]
Error: A JNI error has occurred, please check your installation and try again.

**Comment by Ben-Bingham** [comment]
What version of java do you have installed?

**Comment by V1pr1n** [comment]
Java 8

**Comment by Ben-Bingham** [comment]
Currently the tool only works with Java 16. I plan on recompiling the project on Java 8 so people developing for older versions can still use. I plan to have that done by the end of the week. Until than you’ll have to download Java 16 if you want to Use the tool.
